apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m0h52v9sn-python 
  janus-idp.io/tekton: m0h52v9sn-python
  backstage.io/kubernetes-id: m0h52v9sn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m0h52v9sn-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml