apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m0h52v9sn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m0h52v9sn-python 
  name: m0h52v9sn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: m0h52v9sn-python 
